defaults:
  - net: rnnlm
  - scheduler: cosine_schedule_with_warmup
  - _self_

_target_: src.models.ldc_module.LDCLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.004
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.01
