_target_: src.models.ldc_module.LDCLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.8
  patience: 0
  threshold: 0.0025

net:
  _target_: src.models.components.rnnlm.RNNLM
  output_neurons: 8000
  embedding_dim: 128
  dropout: 0.2
  rnn_neurons: 1024
  rnn_layers: 2
  rnn_re_init: False
  dnn_neurons: 256
