# @package _global_

defaults:
  - _self_
  - data: ldc_cna # choose datamodule with `test_dataloader()` for evaluation
  - model: ldc
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

data:
  batch_size: 512
  tokenizer_model_path: /mnt/md1/user_wayne/TimeLM/tokenizer/ldc_cna_char_8000.model

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
